# Generated by Django 3.0.3 on 2020-06-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CDR', models.FloatField(default=0.1)),
                ('optradio', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='Left', max_length=20)),
                ('optradio1', models.CharField(choices=[('Poor Quality', 'Poor Quality'), ('Ungradable', 'Ungradable'), ('Gradable', 'Gradable')], default='Poor Quality', max_length=20)),
                ('optradio2', models.CharField(choices=[('Disc boundary', 'Disc boundary'), ('Cup boundary', 'Cup boundary')], default='Disc boundary', max_length=20)),
                ('optradio3', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20)),
                ('optradio4', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20)),
                ('optradio5', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20)),
                ('optradio6', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20)),
                ('optradio7', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='image_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exampleRadios1', models.CharField(choices=[('Diabetic Retinopathy (DR)', 'Diabetic Retinopathy (DR)'), (' Glaucoma', '  Glaucoma'), ('Others', 'Others')], default='Diabetic Retinopathy (DR)', max_length=50)),
                ('Annotations_image', models.ImageField(blank=True, upload_to='assets/img/')),
            ],
        ),
    ]
