# Generated by Django 2.2.10 on 2020-06-29 10:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='image_upload',
            name='Annotations_image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
